spring.application.name=JwtAuthentication

spring.datasource.url=jdbc:postgresql://localhost:5432/Jwt_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update



spring.security.user.username=prasanna
spring.security.user.password=1234